// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace TestApp
{
	public partial class InitialViewController : NSViewController
	{
		public InitialViewController (IntPtr handle) : base (handle)
		{
		}

        public override void PrepareForSegue(NSStoryboardSegue segue, NSObject sender)
        {
            base.PrepareForSegue(segue, sender);

            switch (segue.Identifier)
            {
                case "LaunchChat":
                    {
                        ChatViewController target = segue.DestinationController as ChatViewController;
                        target.Username = usernameTextField.StringValue;
                        target.Topic = topicTextField.StringValue;
                        View.Window.Close();
                    }
                    break;
            }
        }
    }
}
